# Kubernetes Deployment File
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbtest
  template:
    metadata:
      labels:
        app: sbtest
    spec:
      containers:
        - name: nodejs
          image: olyumpus/veltrix-project:${IMAGE_TAG}
          ports:
            - containerPort: 3000  # Adjust the port if your application listens on a different port
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsservice
spec:
  selector:
    app: sbtest
  ports:
    - protocol: TCP
      port: 3000  # Port inside the cluster
      targetPort: 3000  # Port your application listens on
  type: NodePort
