apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 2
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: {}
  selector:
    matchLabels:
      app: sbtest
  template:
    metadata:
      labels:
        app: sbtest
    spec:
      containers:
        - name: nodejs
          image: olyumpus/nodejstest:2
          ports:
            - containerPort: 3000  # Adjust the port if your application listens on a different port
