---
apiVersion: v1
kind: Service
metadata:
  name: nodejsservice
spec:
  selector:
    app: sbtest
  ports:
    - protocol: TCP
      port: 3000  # Port inside the cluster
      targetPort: 3000  # Port your application listens on
  type: NodePort
