name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update apt-get
      run: sudo apt-get update && sudo apt-get install -y curl
      
    - name: Install apt-transport-https
      run: sudo apt-get install -y apt-transport-https
      
    - name: Add Google Cloud apt key
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.28.2/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Add Kubernetes repository to apt sources
      run: echo "deb https://apt.kubernetes.io/kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
    
    - name: Decrypt kubeconfig
      run: |
        echo "$KUBECONFIG" | base64 -d > kubeconfig.yaml

    - name: Configure kubectl
      run: |
        mkdir ~/.kube
        mv kubeconfig.yaml ~/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl get pods
