name: Veltrix

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm run

    - name: Build
      run: npm install
      
    - name: Build Docker image
      run: |
        IMAGE_NAME=olyumpus/veltrix-project
        IMAGE_TAG=${{ github.sha }}
        docker build -t $IMAGE_NAME:$IMAGE_TAG .

    - name: Push Docker image to Docker Hub
      run: |
        docker login -u olyumpus -p ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME=olyumpus/nodejstest
        IMAGE_TAG=${{ github.sha }}
        docker push $IMAGE_NAME:$IMAGE_TAG
    
      







      
