name: My Project Checkout and Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm run

    - name: Build
      run: npm install
      
    - name: Build Docker image
      run: |
        docker build -t olyumpus/nodejstest:1 .

    - name: Push Docker image to Docker Hub
      run: |
        docker login -u olyumpus -p ${{ secrets.DOCKER_PASSWORD }}
        docker push olyumpus/nodejstest:1

    - name: Run Docker Conatiner
      run: |
        docker run -d --name nodejstest -p 3000:3000 olyumpus/nodejstest:1

    - name: Download and setup ngrok
      run: |
        wget -q -O /tmp/ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip -o /tmp/ngrok.zip -d /usr/local/bin
       

    - name: Start ngrok
      run: |
        ngrok config add-authtoken ${{ secrets.NGROK_PASSWORD }}
        ngrok http 3000


      
