name: My Project Checkout and Build.s

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm run

    - name: Build
      run: npm install
      
    - name: Build Docker image
      run: |
        docker build -t olyumpus/nodejstest:1 .

    - name: Push Docker image to Docker Hub
      run: |
        docker login -u olyumpus -p ${{ secrets.DOCKER_PASSWORD }}
        docker push olyumpus/nodejstest:1

    - name: Run Docker Conatiner
      run: |
        # docker run -d --name nodejstest -p 3000:3000 olyumpus/nodejstest:1

    - name: Authenticate with AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
        
    - name: Configure kubectl
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.RKUBECONFIG }}
        version: 'latest'
        
    - name: Test kubectl commands
      run: |
        kubectl get pods
        kubectl get deployments
        kubectl version







      
